version: '3'

services:
  api:
    container_name: api
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    env_file:
     - .env
    
    develop:
      watch:
        - action: sync
          path: ./
          target: /app/src
        - action: rebuild
          path: ./package.json
          target: /app/package.json
  db:
    image: postgres:15.6-bookworm
    container_name: POSTGRES_DB
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -d ${DB_NAME} -U ${DB_USERNAME}']
      interval: 1s
      timeout: 5s
      retries: 10
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  pgdata:
